language: python
python:
  - 2.7
install:
  - CFLAGS=-O0 pip install lxml
  - pip install -r dev_requirements.txt
script:
  - python setup.py test
  - flake8 .
notifications:
  email:
  - ci-notify@fulfil.io
